// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qibupwyfwdfjeijaqniu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpYnVwd3lmd2RmamVpamFxbml1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODk2MTQsImV4cCI6MjA2NDU2NTYxNH0.nxIaP55v8kpoGMF4Jk04gnMg4ps0sIxCS-zMdURgYtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);